apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: welcome-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: ENV
              value: "development"