services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: testing/welcome
    container_name: welcome-app
    ports:
      - "8000:5000"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M