apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: welcome-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - welcome.ardidafa.glanze.site
      secretName: welcome-tls
  rules:
    - host: welcome.ardidafa.glanze.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: welcome-service
                port:
                  number: 80