name: CI/CD Pipeline WelcomeApps

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build and deploy'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/welcome:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/welcome:${{ github.event.inputs.release_tag }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/welcome-app welcome-app=${{ secrets.DOCKERHUB_USERNAME }}/welcome:${{ github.event.inputs.release_tag }} -n welcome-app
          kubectl rollout status deployment/welcome-app -n welcome-app

      - name: Verify Deployment
        run: |
          kubectl get deployment welcome-app -n welcome-app
          kubectl get pods -l app=welcome-app -n welcome-app